# Generated by Django 4.2.30 on 2026-04-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('dlc_count', models.IntegerField()),
                ('windows', models.BooleanField()),
                ('mac', models.BooleanField()),
                ('linux', models.BooleanField()),
                ('metacritic_score', models.FloatField(null=True)),
                ('achievements', models.IntegerField(null=True)),
                ('recommendations', models.IntegerField(null=True)),
                ('supported_languages', models.JSONField()),
                ('full_audio_languages', models.JSONField()),
                ('developers', models.JSONField()),
                ('publishers', models.JSONField()),
                ('categories', models.JSONField()),
                ('genres', models.JSONField()),
                ('score_rank', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('average_playtime_forever', models.FloatField()),
                ('average_playtime_2weeks', models.FloatField()),
                ('median_playtime_forever', models.FloatField()),
                ('median_playtime_2weeks', models.FloatField()),
                ('discount', models.FloatField()),
                ('peak_ccu', models.IntegerField()),
                ('tags', models.JSONField()),
                ('pct_pos_total', models.FloatField()),
                ('num_reviews_total', models.IntegerField()),
                ('pct_pos_recent', models.FloatField()),
                ('num_reviews_recent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
