# Generated by Django 4.2.30 on 2026-04-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_game_weather_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('temp_max', models.FloatField(null=True)),
                ('temp_min', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
